name: "Docs Check"
on: pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: |
          pip install -r docs/requirements.txt
        build-command: "sphinx-build -b html . ../build/html"
        docs-folder: "docs/source/"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/
